var palavras = [
    "ALEMANHA",
    "CAMAROES",
    "INGLATERRA",
    "PORTUGAL",
    "VATICANO",
    "GALINHADA",
    "BISCOITO",
    "CHOCOLATE",
    "AFETO",
    "SAUDADES",
    "HTML",
    "ALURA",
    "CSS",
    "VERMELHO",
    "GATO",
    "DESAFIO",
    "LIVE",
    "JAVASCRIPT",
    "TURQUESA",
    "TURQUIA",
    "FRONTEND",
    "STYLE",
    "TRELLO",
    "CODAR",
    "INSTRUTORES",
    "NICIANTE",
    "GOL",
    "RANGER",
    "GOLF",
    "CIVIC",
    "COLOLLA",
    "HILLUX",
    "FIORINO",
    "PARATI",
    "JETTA",
    "GOIANIA",
    "BRAZILIA",
    "MORRINHOS",
    "CUIABA",
    "PELOTAS",
    "CODAR",
    "CEARA",
    "TEREZOPOLIS",
    "GUARULHOS",
    "PIRINOPOLIS",
    "GOIAS",
    "MONICA",
    "CARUARU",
    "TECNOLOGIA",
    "VIOLETA",
    "BRANCO",
    "TURQUESA",
    "FERNANDO",
    "DAMASCO",
    "MAGENTA",
    "CARAMELO",
    "VERMELHO",
    "MARROM",
    "MAGENTA",
    "FACEBOOK",
    "INSTAGRAN",
    "ALEGRIA",
    "TRISTEZA",
    "RAIVA",
    "SONO",
    "FELICIDADE",
    "HOSTILIDADE",
    "MEDO",
    "EMPATIA",
    "AFETO",
    "CACHORRO",
    "GATO",
    "VENCEDOR",
    "SORTE",
    "SALADA",
    "GARRAFA",
    "AFRICA",
    "BRASIL"

];

function palavraAleatoria() {
    palavraSecreta = palavras[Math.floor(Math.random() * palavras.length)].toUpperCase()
}


const letrasErradas = []
const letrasCorretas = [];